$NetBSD: patch-Cargo.toml,v 1.3 2024/12/26 12:01:54 wiz Exp $

Depends on unpublished crates. Can't use cargo.mk to fetch it.

--- Cargo.toml.orig	1970-01-01 00:00:00.000000000 +0000
+++ Cargo.toml
@@ -25,7 +25,7 @@ rust-version = "1.63"
 
 [dependencies]
 crossbeam-channel = "0.5.12"
-notify = {git = "https://github.com/samuelcolvin/notify.git", branch = "keep-io-error"}
+notify = {path = "../notify-0f87ab12707d231fa44180454d59478d3992eb59/notify"}
 pyo3 = { version = "0.23.3", features = ["extension-module", "generate-import-lib"] }
 
 [lib]
