$NetBSD: patch-pyproject.toml,v 1.1 2025/01/07 13:29:49 wiz Exp $

Support poetry-core 2.0.0.
https://github.com/python-poetry/poetry/issues/9985

--- pyproject.toml.orig	2025-01-07 13:21:49.773836629 +0000
+++ pyproject.toml
@@ -1,6 +1,7 @@
-[tool.poetry]
+[project]
 name = "anytree"
 version = "2.12.1"
+[tool.poetry]
 description = "Powerful and Lightweight Python Tree Data Structure with various plugins"
 authors = [
     "c0fec0de <c0fec0de@gmail.com>"
